doctor
update
upgrade

install coreutils
install findutils
install libarchive
install spatialite-tools
install readline
install rsync

install fish
install ssh-copy-id
install wget --enable-iri

install git
install git-extras

# Utilities
install ack
install htop-osx
install httpie
install jq
install rename
install tree

# Taps
tap homebrew/dupes

# Install more recent versions of some OS X tools
install vim --with-override-system-vi
install homebrew/dupes/grep

# Dev
install go
install saltstack
install ansible
install packer
install terraform

cleanup
